
name: 'olist_analytics'
version: '1.0.0'
config-version: 2

# This setting tells dbt which profile to use from profiles.yml
profile: 'olist_project'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

# Configuring models
models:
  olist_analytics:
    # Config for all models
    materialized: table # Default to table for DuckDB (simpler than view)
    
    staging:
      materialized: view # Staging as views is fine
      schema: staging

    marts:
      materialized: table
      schema: marts
