
version: 2

models:
  - name: stg_orders
    description: "Staging model for orders data"
    columns:
      - name: order_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'processing', 'canceled', 'invoiced', 'unavailable', 'created', 'approved']

  - name: stg_customers
    description: "Staging model for customers data"
    columns:
      - name: customer_id
        description: "Primary key per order"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Unique identifier for a customer"
        tests:
          - not_null

  - name: stg_products
    description: "Staging model for products data"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Category name in Portuguese"

  - name: stg_order_items
    description: "Staging model for order items"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: order_item_id
        tests:
          - not_null
      # Composite key test could be added (order_id + order_item_id)
      - name: price
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

  - name: stg_sellers
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: stg_order_payments
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_value
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
