
version: 2

sources:
  - name: olist
    schema: main # Default schema in DuckDB
    tables:
      - name: bronze_orders
      - name: bronze_order_items
      - name: bronze_products
      - name: bronze_sellers
      - name: bronze_customers
      - name: bronze_order_payments
      - name: bronze_order_reviews
      - name: bronze_geolocation
      - name: bronze_product_category_translation
